### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-frontend-documentation#19]
Bonjour,
à partir de la documentation FR : 
https://karutaproject.github.io/karuta-frontend-documentation/documentation_fr/
Lorsque l'on clique sur "Portfolio" on arrive sur une erreur 404 : 

https://karutaproject.github.io/karuta-frontend-documentation/documentation_fr/portfolio_fr.html

**Comment by Badatos** [comment]
L'adresse exacte semble être la suivante : 
https://karutaproject.github.io/karuta-frontend-documentation/portfolio_fr/

**Comment by olivier-gerbe** [comment]
Bonjour,
Je n'arrive pas à reproduire. Je vais régulièrement sur le site et pas de problème
Olivier

**Comment by Badatos** [comment]
J'ai du mal à voir comment le lien suivant : 
https://karutaproject.github.io/karuta-frontend-documentation/documentation_fr/portfolio_fr.html
... pourrait me donner une erreur 404 mais pas pour vous.

Ceci dit, je clique sur les liens à l'intérieur de la page et non dans le menu du haut.

**Comment by olivier-gerbe** [comment]
Done
